import "server-only";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import { R2_BUCKET, r2Configured, withR2 } from "@/lib/r2";
import { propolyUpload, PropolyWriteBlocked } from "@/lib/business/propoly";
import { getAllPropolyDeals } from "@/lib/business/propoly-deals";
import { propertyKey } from "@/lib/business/payprop-portfolio";
import { getCase, recordPropolyPush } from "@/lib/plc-store";
import { checkById, type CheckId, type PlcCase, type PlcDocument, type PropolyPush, type PushResult } from "@/lib/plc";

/**
 * The approved pack, into Propoly's document slots.
 *
 * Kirstie (4 Sep): "we're going to need to take all the PLC docs, and when we
 * send it to you, we'll also need to put them into Propoly docs, because
 * otherwise you're not going to be able to move the deal forward." Today she
 * uploads them again by hand. This does it from the pack she just approved.
 *
 * ── The slots ─────────────────────────────────────────────────────────────
 *
 * Propoly has seventeen named document types per deal (read live, 4 Sep) and
 * takes one file per type. The OS's nine checks do not map one to one:
 * "Landlord ID & AML" holds ID, proof of address and the AML report as three
 * files, and which is which is only knowable from the filename. So each file
 * is placed by check and then by name, and anything that fits nowhere goes
 * in as a General Document rather than not at all - a file in the wrong slot
 * is a click for Kirstie, a missing one is a failed check.
 *
 * ── Expiry ────────────────────────────────────────────────────────────────
 *
 * Gas, EPC and EICR need an expiry date or Propoly rejects them. The date
 * the reader found on the document is used (findings.foundDate); with none
 * read, the file is skipped and the reason recorded, because inventing a
 * date on a safety certificate is not a shortcut anybody should take.
 *
 * ── It never throws past the switch ───────────────────────────────────────
 *
 * Every document gets an outcome and the whole run is written to the case.
 * The one thing that stops it outright is the switch being off, which is
 * reported as a single skipped run rather than nine identical refusals.
 */

const COMPLIANCE_TYPES = new Set([
  "DealGasSafetyAttachment",
  "DealEpcAttachment",
  "DealElectricalInstallationAttachment",
  "DealPortableApplianceTestAttachment",
  "DealLegionellaRiskAssessmentAttachment",
]);

/** Which Propoly slot a file belongs in, by check and then by filename. */
export function propolyTypeFor(checkId: CheckId, name: string): string | null {
  const n = name.toLowerCase();
  switch (checkId) {
    case "landlord-id-aml":
      if (/aml|money.?laund|kyc/.test(n)) return "DealLandlordAmlCheckAttachment";
      if (/address|utility|council.?tax|bank|statement|bill/.test(n)) return "DealLlProofOfAddressAttachment";
      if (/ownership|title|land.?reg|deeds|mortgage/.test(n)) return "DealLlProofOfOwnershipAttachment";
      return "DealLlIdAttachment";
    case "tenant-checks":
      return "DealTtReferenceReportAttachment";
    case "guarantor-checks":
      return "DealGeneralAttachment";
    case "gas-safety":
      return "DealGasSafetyAttachment";
    case "epc":
      return "DealEpcAttachment";
    case "eicr":
      return "DealElectricalInstallationAttachment";
    case "licensing":
      return /requirement|exempt|not.?required/.test(n) ? "DealLicensingRequirementsAttachment" : "DealCouncilLicenseAttachment";
    case "right-to-rent":
      return "DealTtRightToRentAttachment";
    case "tenancy-agreement":
      /* Generated by Kirstie in Propoly after the check. Never pushed. */
      return null;
    default:
      return "DealGeneralAttachment";
  }
}

function expiryFor(c: PlcCase, checkId: CheckId): string | null {
  const f = c.findings.find((x) => x.checkId === checkId && x.foundDate);
  return f?.foundDate ?? null;
}

async function bytesOf(doc: PlcDocument): Promise<{ bytes: Uint8Array; type: string }> {
  if (doc.placeholder) throw new Error("recorded by name only, never stored");
  if (!r2Configured) throw new Error("file storage isn't configured here");
  return withR2(async (client) => {
    const res = await client.send(new GetObjectCommand({ Bucket: R2_BUCKET, Key: doc.key }));
    const bytes = await res.Body?.transformToByteArray();
    if (!bytes) throw new Error("the stored file came back empty");
    const type = res.ContentType || (doc.name.toLowerCase().endsWith(".pdf") ? "application/pdf" : "application/octet-stream");
    return { bytes, type };
  });
}

/** The Propoly deal for this pack's address. Same loose key the board uses. */
export async function propolyDealForCase(c: PlcCase): Promise<string | null> {
  const key = propertyKey(c.address);
  if (!key) return null;
  const deals = await getAllPropolyDeals().catch(() => null);
  if (!deals) return null;
  const live = deals.filter((d) => d.statusKey !== "cancelled" && d.statusKey !== "complete");
  const hit = live.find((d) => propertyKey(d.app.propertyName) === key) ?? deals.find((d) => propertyKey(d.app.propertyName) === key);
  return hit?.app.id ?? null;
}

export async function pushCaseToPropoly(caseId: string, by: string): Promise<PropolyPush> {
  const c = await getCase(caseId);
  if (!c) throw new Error("That pack no longer exists.");
  if (c.state !== "approved") throw new Error("Only an approved pack goes into Propoly.");

  const at = new Date().toISOString();
  const dealId = await propolyDealForCase(c);
  if (!dealId) {
    const push: PropolyPush = {
      at,
      by,
      dealId: null,
      results: c.documents.map((d) => ({
        checkId: d.checkId,
        name: d.name,
        type: propolyTypeFor(d.checkId, d.name),
        outcome: "skipped",
        note: "No Propoly deal found for this address.",
      })),
    };
    await recordPropolyPush(caseId, push);
    return push;
  }

  const results: PushResult[] = [];
  const taken = new Set<string>();
  for (const doc of c.documents) {
    const type = propolyTypeFor(doc.checkId, doc.name);
    const label = checkById(doc.checkId)?.label ?? doc.checkId;
    if (!type) {
      results.push({ checkId: doc.checkId, name: doc.name, type: null, outcome: "skipped", note: `${label} is generated in Propoly after the check.` });
      continue;
    }
    if (taken.has(type)) {
      results.push({ checkId: doc.checkId, name: doc.name, type, outcome: "skipped", note: "Propoly takes one file per slot and this slot already had one from this pack." });
      continue;
    }
    const expiry = COMPLIANCE_TYPES.has(type) ? expiryFor(c, doc.checkId) : null;
    if (COMPLIANCE_TYPES.has(type) && !expiry) {
      results.push({ checkId: doc.checkId, name: doc.name, type, outcome: "skipped", note: "Propoly needs an expiry date for this and the reader did not find one on the document." });
      continue;
    }
    try {
      const { bytes, type: mime } = await bytesOf(doc);
      const form = new FormData();
      form.set("deal_id", dealId);
      form.set("type", type);
      form.set("name", doc.name);
      if (expiry) form.set("expiration", expiry);
      /* Copied into a plain ArrayBuffer: the S3 client hands back a view over
         a buffer the Blob constructor will not accept as-is. */
      const copy = new Uint8Array(bytes.byteLength);
      copy.set(bytes);
      form.set("attached", new Blob([copy.buffer], { type: mime }), doc.name);
      const res = await propolyUpload("/api/v1/documents", form);
      const msg = (res.body as { message?: string } | null)?.message ?? "";
      if (res.status === 201 || res.status === 200) {
        taken.add(type);
        results.push({ checkId: doc.checkId, name: doc.name, type, outcome: "uploaded", note: "Uploaded." });
      } else if (res.status === 409 || /already exists/i.test(msg)) {
        taken.add(type);
        results.push({ checkId: doc.checkId, name: doc.name, type, outcome: "already", note: "Propoly already holds a document in this slot." });
      } else {
        results.push({ checkId: doc.checkId, name: doc.name, type, outcome: "failed", note: msg || `Propoly answered ${res.status}.` });
      }
    } catch (e) {
      if (e instanceof PropolyWriteBlocked) {
        results.push({ checkId: doc.checkId, name: doc.name, type, outcome: "skipped", note: "Pushing documents into Propoly is switched off (Admin, Switches)." });
        continue;
      }
      results.push({ checkId: doc.checkId, name: doc.name, type, outcome: "failed", note: e instanceof Error ? e.message : "upload failed" });
    }
  }

  const push: PropolyPush = { at, by, dealId, results };
  await recordPropolyPush(caseId, push);
  return push;
}
