/**
 * The PLC handover: agent → compliance → back to agent.
 *
 * When an application is accepted the file stops being the agent's and becomes
 * a submission. Somebody has to assemble the documents, somebody else has to
 * check them, and the property cannot be let until they say so. Today that
 * happens in email, which is why nobody can answer "where is 41 Harewood up
 * to" without asking Kirstie.
 *
 * ── The one rule that shapes everything here ────────────────────────────────
 *
 * THE SCAN DOES NOT DECIDE. It reads documents and reports what it found -
 * a date, a name, a missing page. Whether a file is compliant is a legal
 * judgement with a person's name against it, and that person is Kirstie. So
 * the model produces FINDINGS, never a verdict, and the case cannot leave
 * review without a human pressing something.
 *
 * That is not caution for its own sake. If the scan could approve, then the
 * day it misreads an expiry we have let a property with an out-of-date gas
 * certificate and the audit trail says a computer decided. The scan exists to
 * make Kirstie faster, not to replace her.
 *
 * ── Checks ──────────────────────────────────────────────────────────────────
 *
 * Taken from what Legal for Landlords actually cover for us (James, 29 Aug),
 * so the OS asks for the same pack we already send them rather than inventing
 * its own list. Two properties matter per check: what document proves it, and
 * whether a machine can say anything useful about it at all.
 */

/* ───────────────────────────── the checks ───────────────────────────────── */

export type CheckId =
  /* Was "Landlord ID & AML" until 7 Oct 2026 (Michael: "they are two separate
     things"). The id is kept so packs filed before the split still read; it
     is the ID now, and AML and proof of ownership have their own boxes. */
  | "landlord-id-aml"
  | "landlord-aml"
  | "proof-of-ownership"
  | "tenant-checks"
  | "guarantor-checks"
  | "gas-safety"
  | "epc"
  | "eicr"
  | "licensing"
  | "tenancy-agreement"
  | "right-to-rent"
  /* The signed holding deposit form (Michael, 7 Oct 2026). */
  | "holding-deposit"
  /* The HMO set (6 Oct 2026, Rhiannon's room at 5b Newton Road): a room in a
     shared house cannot be checked without them, and there was nowhere to
     put a PAT test. Asked of every pack, required only of an HMO. */
  | "pat"
  | "fire-safety"
  | "emergency-lighting"
  | "alarms"
  | "legionella"
  /* Whatever the reader could not place. Never required, never pushed. */
  | "other";

/**
 * What kind of let the pack is for. Decides which of the HMO documents are
 * needed (James, 6 Oct 2026: "this property is an HMO, and therefore it needs
 * a PAT test"). Asked on the first screen, guessed from the property.
 */
export type LetType = "home" | "hmo";

export type Check = {
  id: CheckId;
  label: string;
  /** What the agent has to attach for this to be checkable at all. */
  needs: string;
  /**
   * What the scan can genuinely say.
   *
   * `dates`    — it can read an expiry and compare it to the move-in date.
   * `presence` — it can say a document is there and looks like what it claims.
   * `reading`  — it can pull named fields out and flag disagreements.
   * `none`     — a human judgement the model should not be asked to make.
   *
   * Recorded per check so the UI can be honest about which lines the scan
   * actually looked at, rather than implying it understood all nine.
   */
  scan: "dates" | "presence" | "reading" | "none";
  /** Why it is on the list, in the words somebody would use out loud. */
  why: string;
  /**
   * Whether the pack can leave the agent without it.
   *
   * `required`    - it cannot. Every let needs one and there is no reason
   *                 that satisfies the check. The send button stays off.
   * `conditional` - usually needed, but a real reason removes it: a flat
   *                 with no gas supply, a council that licenses nothing, a
   *                 tenant with no guarantor. The agent says why, in writing,
   *                 and Kirstie reads the reason next to the empty slot.
   * `after`       - not part of the pre-let check at all. The tenancy
   *                 agreement is generated by Kirstie once the check has
   *                 passed (her words, 4 Sep), so asking for it first is
   *                 asking for a thing that does not exist yet.
   * `manual`      - Right to Rent: evidence may legitimately live elsewhere.
   * `optional`    - worth having on file, never asked for. The HMO set on
   *                 an ordinary home, and anything unsorted.
   *
   * This is the £60 rule. A pack that reaches Legal for Landlords with an
   * empty slot fails, and the failed check is charged again to TLE rather
   * than to the agent. So the empty slot is caught here, where it costs a
   * sentence, rather than there, where it costs sixty pounds.
   */
  gate: Gate;
  /** The gate instead, when the let is an HMO. */
  hmoGate?: Gate;
};

export type Gate = "required" | "conditional" | "after" | "manual" | "optional";

export const PLC_CHECKS: Check[] = [
  {
    id: "landlord-id-aml",
    label: "Landlord ID",
    needs: "Photo ID for every named owner - add one for each landlord",
    scan: "reading",
    why: "We have to know who we are acting for, and every owner on the title signs.",
    gate: "required",
  },
  {
    id: "landlord-aml",
    label: "Landlord AML",
    needs: "The AML check and proof of address for every named owner - add one for each landlord",
    scan: "reading",
    why: "Money laundering checks are on the agent, not the landlord, and the fine lands here.",
    gate: "required",
  },
  {
    id: "proof-of-ownership",
    label: "Proof of ownership",
    needs: "Land Registry title, or the mortgage or deeds naming the owners",
    scan: "reading",
    why: "The people giving us the keys have to be the people who own the home.",
    gate: "optional",
  },
  {
    id: "tenant-checks",
    label: "Tenant checks",
    needs: "Referencing outcome for each tenant",
    scan: "reading",
    why: "Affordability and history, per person on the tenancy rather than per household.",
    gate: "required",
  },
  {
    id: "guarantor-checks",
    label: "Guarantor checks",
    needs: "Referencing outcome and signed guarantee, where one is required",
    scan: "reading",
    why: "A guarantor who was never referenced is a guarantee nobody can enforce.",
    gate: "conditional",
  },
  {
    id: "gas-safety",
    label: "Gas safety",
    needs: "Current CP12, dated within 12 months",
    scan: "dates",
    why: "Must be in date ON the move-in date, not on the day it was uploaded.",
    gate: "conditional",
  },
  {
    id: "epc",
    label: "EPC",
    needs: "Certificate rated E or above",
    scan: "dates",
    why: "Below E cannot be let without an exemption, and the exemption is its own document.",
    gate: "required",
  },
  {
    id: "eicr",
    label: "EICR",
    needs: "Satisfactory report, dated within 5 years",
    scan: "dates",
    why: "An 'unsatisfactory' report with remedial work outstanding is not a pass.",
    gate: "required",
  },
  {
    id: "licensing",
    label: "Licensing",
    needs: "Selective or HMO licence, where the council requires one",
    scan: "presence",
    why: "Council-by-council and changes without notice, so absence is a question rather than a fail.",
    gate: "conditional",
  },
  {
    id: "right-to-rent",
    label: "Right to Rent",
    needs: "Share code or original document check for each adult occupier",
    scan: "none",
    why: "A statutory check with a manual step. The model must not be asked to certify it.",
    gate: "manual",
  },
  {
    id: "holding-deposit",
    label: "Holding deposit form, signed",
    needs: "The holding deposit form the tenant signed",
    scan: "presence",
    why: "A holding deposit taken without the signed terms has to be handed back.",
    gate: "conditional",
  },
  {
    id: "tenancy-agreement",
    label: "Tenancy agreement",
    needs: "The agreement as it will be signed",
    scan: "reading",
    why: "Names, dates, rent and deposit have to match the rest of the pack.",
    gate: "after",
  },
  {
    id: "pat",
    label: "PAT test",
    needs: "Portable appliance test report, within 12 months",
    scan: "dates",
    why: "Appliances the landlord supplies in a shared house have to be tested.",
    gate: "optional",
    hmoGate: "conditional",
  },
  {
    id: "fire-safety",
    label: "Fire risk assessment",
    needs: "Current fire risk assessment, plus the fire alarm certificate where one is fitted",
    scan: "dates",
    why: "Every HMO needs one, and the council asks for it before anything else.",
    gate: "optional",
    hmoGate: "conditional",
  },
  {
    id: "emergency-lighting",
    label: "Emergency lighting",
    needs: "Emergency lighting test certificate, usually yearly",
    scan: "dates",
    why: "Where a shared house has emergency lighting, it has to be tested and the test kept.",
    gate: "optional",
    hmoGate: "conditional",
  },
  {
    id: "alarms",
    label: "Smoke and CO alarms",
    needs: "Test record or certificate for the smoke and carbon monoxide alarms",
    scan: "presence",
    why: "Alarms must be working on the day the tenancy starts.",
    gate: "optional",
    hmoGate: "conditional",
  },
  {
    id: "legionella",
    label: "Legionella risk assessment",
    needs: "Legionella risk assessment, usually reviewed every 2 years",
    scan: "dates",
    why: "A duty on every let in Scotland, and good practice on any shared water system.",
    gate: "optional",
  },
  {
    id: "other",
    label: "Anything else",
    needs: "Inventory, floor plan, or anything we could not sort",
    scan: "none",
    why: "Somewhere for the files that are not one of the checks, so nothing is lost.",
    gate: "optional",
  },
];

/** The gate that applies to this pack. */
export const gateOf = (check: Check, letType: LetType | null | undefined): Gate =>
  letType === "hmo" && check.hmoGate ? check.hmoGate : check.gate;

export const checkById = (id: CheckId) => PLC_CHECKS.find((c) => c.id === id) ?? null;

/* ──────────────────────────── how they're asked ────────────────────────── */

/**
 * The pack, in the two piles an agent actually holds it in.
 *
 * Nine upload boxes on one screen reads as a chore and gets half-filled. Split
 * in two it reads as two errands, and each one is a set of documents that come
 * from the same place: the landlord's pile arrives from the landlord and the
 * managing agent, the tenant's from referencing and the application.
 *
 * The grouping is presentational and lives here rather than in the wizard, so
 * a tenth check has one obvious home instead of being quietly left out of
 * whichever screen nobody remembered to edit.
 */
export const CHECK_GROUPS: { id: "landlord" | "tenant"; title: string; blurb: string; checks: CheckId[] }[] = [
  {
    id: "landlord",
    title: "Landlord Documents",
    blurb: "The landlord's ID and every certificate for the property.",
    checks: ["landlord-id-aml", "landlord-aml", "proof-of-ownership", "gas-safety", "epc", "eicr", "licensing", "pat", "fire-safety", "emergency-lighting", "alarms", "legionella"],
  },
  {
    id: "tenant",
    title: "Tenant Documents",
    blurb: "Referencing, guarantors and Right to Rent for everyone moving in.",
    checks: ["tenant-checks", "guarantor-checks", "right-to-rent", "holding-deposit", "tenancy-agreement"],
  },
];

/** Which step a check is filed under. "Anything else" lives on the landlord step. */
export const groupOf = (id: CheckId): "landlord" | "tenant" =>
  CHECK_GROUPS.find((g) => g.checks.includes(id))?.id ?? "landlord";

/**
 * A first guess at which check a dropped file belongs to.
 *
 * A guess, and it is presented as one: the wizard shows the answer in a control
 * the agent can change, never as a decision already made. Filing an EICR as a
 * gas certificate because a filename said "certificate" would send a wrong
 * document to compliance with a confident label on it, which is worse than
 * asking.
 *
 * Order matters. "gas safety certificate.pdf" contains both "gas" and
 * "certificate", so the specific patterns are tried before the loose ones.
 */
const FILENAME_HINTS: [RegExp, CheckId][] = [
  [/\bpat\b|portable.?appliance/i, "pat"],
  [/legionella/i, "legionella"],
  [/emergency.?light/i, "emergency-lighting"],
  [/fire.?risk|\bfra\b|fire.?alarm|fire.?door/i, "fire-safety"],
  [/holding.?deposit/i, "holding-deposit"],
  [/ownership|title.?(plan|register)|land.?reg|deeds/i, "proof-of-ownership"],
  [/\baml\b|anti.?money|money.?laund|kyc|proof.?of.?address|utility|council.?tax/i, "landlord-aml"],
  [/smoke|carbon.?monoxide|\bco.?alarm|alarm/i, "alarms"],
  [/cp-?12|gas/i, "gas-safety"],
  [/eicr|electric|nice?ic|periodic.?inspect/i, "eicr"],
  [/epc|energy.?perf/i, "epc"],
  [/licen[cs]|hmo|selective/i, "licensing"],
  /* A referencing report, before "landlord": "Legal for Landlords reference.pdf"
     is the tenant's, not the landlord's ID. */
  [/referenc|goodlord|homelet|let.?alliance/i, "tenant-checks"],
  /* The landlord's own passport is ID, not Right to Rent: checked before the
     passport pattern below catches it. */
  [/landlord|\bll\b|owner/i, "landlord-id-aml"],
  [/guarantor|guarantee/i, "guarantor-checks"],
  [/right.?to.?rent|share.?code|passport|visa|brp/i, "right-to-rent"],
  [/ast|tenancy.?agree|agreement/i, "tenancy-agreement"],
  [/referenc|goodlord|rightmove|van.?mildert|credit/i, "tenant-checks"],
  [/landlord.?id|\bid\b|driving/i, "landlord-id-aml"],
];

/** Null when nothing matched, which the wizard shows as "choose a check". */
export function guessCheck(filename: string, within?: CheckId[]): CheckId | null {
  for (const [re, id] of FILENAME_HINTS) {
    if (!re.test(filename)) continue;
    if (within && !within.includes(id)) continue;
    return id;
  }
  return null;
}

/* ───────────────────────────── the states ──────────────────────────────── */

export type PlcState =
  /** The agent is still putting the pack together. Nobody is waiting on us. */
  | "assembling"
  /** Handed to compliance. The agent can no longer change it. */
  | "submitted"
  /** The model is reading the documents. */
  | "scanning"
  /** Findings are in. The first check (Josel) has not passed it yet. */
  | "reviewing"
  /** First check done. Waiting on Kirstie or Michael for the final approval. */
  | "checked"
  | "approved"
  /** Something is missing or wrong; it goes back to the agent to fix. */
  | "deferred"
  | "declined";

export const PLC_STATES: { id: PlcState; label: string; who: string; blurb: string }[] = [
  { id: "assembling", label: "Assembling", who: "Agent",
    blurb: "Attaching the pack. Nothing has gone to compliance." },
  { id: "submitted", label: "Submitted", who: "Compliance",
    blurb: "With the PLC team. Locked to the agent from here." },
  { id: "scanning", label: "Scanning", who: "The OS",
    blurb: "Reading the documents for dates and details." },
  { id: "reviewing", label: "First check", who: "Compliance",
    blurb: "Findings are in. Josel checks every document against the pack before it goes further." },
  { id: "checked", label: "Final approval", who: "Kirstie or Michael",
    blurb: "Checked once. Kirstie or Michael gives the final approval." },
  { id: "approved", label: "Approved", who: "Agent",
    blurb: "Cleared. The property can be let." },
  { id: "deferred", label: "Deferred", who: "Agent",
    blurb: "Something is missing. Back to the agent, with the reason." },
  { id: "declined", label: "Declined", who: "Agent",
    blurb: "Not proceeding on this pack." },
];

/**
 * What may follow what.
 *
 * Written as data rather than as ifs scattered through routes, because the
 * expensive mistakes here are ordering ones: a pack approved before it was
 * scanned, or an agent editing documents after submission. A transition that
 * is not in this table cannot happen.
 *
 * `deferred` returns to `assembling` on purpose. A deferral is not an ending,
 * it is the agent's turn again, and giving it its own dead-end state would
 * leave real cases stranded with nowhere to go.
 */
export const PLC_TRANSITIONS: Record<PlcState, PlcState[]> = {
  assembling: ["submitted"],
  submitted: ["scanning", "reviewing"], // scanning is skippable when there is no key
  scanning: ["reviewing"],
  /* Two people, in order (James, 30 Sep 2026): the first check reads every
     document, then Kirstie or Michael signs it off. Approval straight from
     reviewing is not in the table, so it cannot happen. Either of them can
     still send it back or decline it at their step. */
  reviewing: ["checked", "deferred", "declined"],
  checked: ["approved", "deferred", "declined"],
  approved: [],
  deferred: ["assembling"],
  declined: [],
};

export const canMove = (from: PlcState, to: PlcState) =>
  PLC_TRANSITIONS[from]?.includes(to) ?? false;

/** Who is being waited on. The question every board exists to answer. */
export const waitingOn = (s: PlcState) => PLC_STATES.find((x) => x.id === s)?.who ?? "—";

/* ──────────────────────────── the findings ─────────────────────────────── */

export type FindingLevel = "blocker" | "query" | "ok";

export type Finding = {
  checkId: CheckId;
  level: FindingLevel;
  /** One sentence a person can act on. Never "see attached". */
  message: string;
  /** What the model read it from, so Kirstie can go and look at the same page. */
  documentName?: string;
  /** The date it found, where the check is a date check. ISO. */
  foundDate?: string | null;
};

/**
 * A document in the pack.
 *
 * `key` is the R2 object key and `url` is the authenticated route that serves
 * it. Both are kept because they answer different questions: the scan needs
 * the key to fetch the bytes server-side, and the screen needs the URL to put
 * it behind a link. Deriving one from the other at the point of use is how a
 * raw bucket path ends up in page HTML.
 */
export type PlcDocument = {
  checkId: CheckId;
  name: string;
  key: string;
  url: string;
  addedAt: string;
  /** Who attached it. A pack is evidence, and evidence has a chain. */
  addedBy: string;
  /**
   * True when the bytes were never stored - a name standing in for a file on
   * an environment with no bucket attached.
   *
   * It exists so that a walkthrough on a laptop can reach the end of the
   * wizard without the screen ever implying a document is on file when it is
   * not. Anything showing a pack must show this, and the scan reports it as
   * unread rather than skipping it quietly.
   */
  placeholder?: boolean;
  /** What the reader made of the file when it was dropped. */
  read?: FileRead | null;
  /** SHA-256 of the bytes, so the same file is never on a pack twice (7 Oct 2026). */
  hash?: string;
  /**
   * Other checks this one document answers (Michael, 7 Oct 2026): a Legal for
   * Landlords reference report carries the tenant's ID, Right to Rent and AML,
   * so filed under Tenant checks it ticks Right to Rent too.
   */
  covers?: CheckId[];
};

/** Which checks a document filed under one check may also answer. */
export const COVERABLE: Partial<Record<CheckId, CheckId[]>> = {
  "tenant-checks": ["right-to-rent"],
};

/**
 * One file, read the moment it lands (James, 6 Oct 2026: "automatically work
 * out what type of document it is ... confirm any validation dates and how
 * long it's valid until"). Facts for the agent to confirm, never a verdict:
 * the agent can move a file to another check, and the full scan still runs
 * when the pack is sent.
 */
export type FileRead = {
  /** The check the reader thinks it is, or null when it could not say. */
  checkId: CheckId | null;
  /** What it is, in a few words: "Gas Safety Record", "Passport". */
  what: string;
  issueDate: string | null;
  expiryDate: string | null;
  /** Set when the expiry was worked out from an issue date and the usual life. */
  expiryDerived?: boolean;
  /** People named on it, for ID and referencing. */
  names: string[];
  confidence: "high" | "medium" | "low";
  note?: string;
  /** Other checks the reader saw this document answer (a reference report's Right to Rent). */
  alsoCovers?: CheckId[];
  at: string;
};

/**
 * A conditional check the agent has said is not needed, and why.
 *
 * The reason is the document. It sits where the file would have been, with
 * the agent's name on it, so that "no gas" is a claim somebody made rather
 * than a slot everybody forgot.
 */
export type Waiver = {
  checkId: CheckId;
  reason: string;
  by: string;
  at: string;
};

/** One document's fate in a push to Propoly. */
export type PushResult = {
  checkId: CheckId;
  name: string;
  /** Propoly's document type key, or null when nothing fits. */
  type: string | null;
  outcome: "uploaded" | "already" | "skipped" | "failed";
  note: string;
};

export type PropolyPush = {
  at: string;
  by: string;
  /** The Propoly deal the files went to, or null when none matched. */
  dealId: string | null;
  results: PushResult[];
};

/**
 * The same pack, written into REX as compliance entries (5 Sep 2026).
 *
 * James: the certificates agents upload live in Propoly, which cannot be
 * read back, so REX's compliance table - the one the tracker and REX PM's
 * own screen read - stays empty. Writing each certificate there on approval,
 * with the file and the expiry, is what makes one upload count everywhere.
 */
export type RexPush = {
  at: string;
  by: string;
  /** The REX property the entries went onto, or null when none matched. */
  propertyId: string | null;
  results: PushResult[];
};

/** One send of the RLP request to Legal for Landlords. */
export type RlpRequest = {
  at: string;
  by: string;
  to: string;
  outcome: "sent" | "failed";
  /** What went with it, or why it did not go. */
  note: string;
  files: string[];
};

export type PlcCase = {
  id: string;
  /** The application this came from. */
  applicationRef: string;
  address: string;
  agentName: string;
  agentEmail: string;
  state: PlcState;
  submittedAt: string | null;
  /** Documents attached at handover, by check. */
  documents: PlcDocument[];
  /** The date the tenancy starts. Every date check is measured against it. */
  moveInDate: string | null;
  /** Ordinary home or HMO. Null until the agent says (older packs). */
  letType?: LetType | null;
  /** What the agent wanted compliance to know. Free text, not a field. */
  agentNote: string;
  /** Conditional checks declared not needed, each with its reason. */
  waivers: Waiver[];
  /** The last push of the approved pack into Propoly. Null until one runs. */
  propolyPush?: PropolyPush | null;
  rexPush?: RexPush | null;
  scannedAt: string | null;
  findings: Finding[];
  /**
   * The first check (James, 30 Sep 2026): who read the pack before it went
   * for final approval, and what they wrote. The email is kept beside the
   * name because the final approver may not be the same person, and names
   * are not unique enough to prove that.
   */
  checkedAt?: string | null;
  checkedBy?: string | null;
  checkedByEmail?: string | null;
  checkNote?: string;
  /**
   * Rent and Legal Protection, as the agent asked for it. Null until they
   * answer, and the pack cannot be sent until they do. It is a request, not
   * cover: the referencing has to qualify, which is compliance's call.
   */
  rlpWanted?: boolean | null;
  /** The last request sent to Legal for Landlords' RLP team. */
  rlpRequest?: RlpRequest | null;
  /** The final decision, the words, and the name against it. */
  decidedAt: string | null;
  decidedBy: string | null;
  decisionNote: string;
  createdAt: string;
};

/**
 * Is the pack even worth submitting?
 *
 * Checked in the OS before it goes anywhere, because a submission that is
 * obviously short wastes a round trip through a person. Right to Rent is
 * excluded: it is a manual check whose evidence may legitimately live
 * elsewhere, and blocking on it would stop every genuine submission.
 */
export function missingDocuments(c: Pick<PlcCase, "documents" | "waivers" | "letType">): Check[] {
  const have = new Set(c.documents.flatMap((d) => [d.checkId, ...(d.covers ?? [])]));
  const waived = new Set((c.waivers ?? []).map((w) => w.checkId));
  return PLC_CHECKS.filter((k) => {
    const g = gateOf(k, c.letType);
    return (g === "required" || g === "conditional") && !have.has(k.id) && !waived.has(k.id);
  });
}

/**
 * The gate, as the send button reads it.
 *
 * `blocked`  - required checks with nothing filed. No reason unblocks them.
 * `askWhy`   - conditional checks with nothing filed and no reason yet.
 * `ready`    - both lists empty. Only then may the pack leave the agent.
 */
export function gateFor(c: Pick<PlcCase, "documents" | "waivers" | "letType">): {
  blocked: Check[];
  askWhy: Check[];
  ready: boolean;
} {
  const short = missingDocuments(c);
  const blocked = short.filter((k) => gateOf(k, c.letType) === "required");
  const askWhy = short.filter((k) => gateOf(k, c.letType) === "conditional");
  return { blocked, askWhy, ready: blocked.length === 0 && askWhy.length === 0 };
}

/**
 * Who gives the final approval, until Admin says otherwise (James, 30 Sep
 * 2026: "Kirstie or Michael"). Emails, because a name on a record is not
 * proof of who pressed the button. The list can be changed from Admin > PLC
 * checks; this is what applies when nobody has.
 */
export const DEFAULT_PLC_APPROVERS = [
  "kirstie.mulholland@thelettingexperts.co.uk",
  "michael.healy@thelettingexperts.co.uk",
];

/** Has the agent said yes or no to Rent and Legal Protection? */
export const rlpAnswered = (c: Pick<PlcCase, "rlpWanted">) => c.rlpWanted === true || c.rlpWanted === false;

export const waiverFor = (c: Pick<PlcCase, "waivers">, id: CheckId): Waiver | null =>
  (c.waivers ?? []).find((w) => w.checkId === id) ?? null;

/**
 * The case id for an application. One pack per application, so the wizard can
 * ask whether one already exists before it offers to start another.
 */
export const caseIdFor = (applicationRef: string) =>
  `plc-${applicationRef.trim().replace(/[^\w-]+/g, "-")}`;

/**
 * The agent's note, without the "Not needed: ..." line a send adds to it.
 *
 * The waivers are written onto the note at the moment the pack goes, so that
 * compliance read them in one place. A pack that comes back and goes again
 * would otherwise carry that line twice, and the agent would see it in their
 * own note box as if they had typed it.
 */
export const agentOwnNote = (note: string) => note.replace(/(?:\n\n)?Not needed: [^\n]*$/, "").trim();

/** The note as it goes to compliance: the agent's words, then the waivers. */
export function noteAsSent(c: Pick<PlcCase, "agentNote" | "waivers">): string {
  const own = agentOwnNote(c.agentNote);
  if (!(c.waivers ?? []).length) return own;
  const line = `Not needed: ${c.waivers
    .map((w) => `${checkById(w.checkId)?.label ?? w.checkId} (${w.reason})`)
    .join("; ")}.`;
  return own ? `${own}\n\n${line}` : line;
}

/** Blockers first, then queries. What Kirstie should read in order. */
export function sortFindings(f: Finding[]): Finding[] {
  const rank: Record<FindingLevel, number> = { blocker: 0, query: 1, ok: 2 };
  return [...f].sort((a, b) => rank[a.level] - rank[b.level]);
}

/**
 * A one-line summary of the scan, for the board.
 *
 * Deliberately never says "passed". The scan does not pass anything - it
 * reports what it saw, and the sentence has to keep that true even when
 * everything looks fine.
 */
export function scanSummary(f: Finding[]): string {
  const blockers = f.filter((x) => x.level === "blocker").length;
  const queries = f.filter((x) => x.level === "query").length;
  if (blockers) return `${blockers} thing${blockers === 1 ? "" : "s"} to fix before this can be let`;
  if (queries) return `${queries} thing${queries === 1 ? "" : "s"} worth a look`;
  return "Nothing flagged. Still needs your eyes.";
}
